name: Release

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number'   
        required: true

jobs:
  build:
    name: Build release
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore 
        
      - name: Publish
        run: dotnet publish ./TexasPPDMLoader/TexasPPDMLoader.csproj -c Release --self-contained true -r win-x64 -p:PublishSingleFile=true
        
      - name: View content
        run: dir D:\a\TexasPPDMLoader\TexasPPDMLoader\TexasPPDMLoader\bin\Release\net6.0\win-x64\publish\
        
      - name: Upload TexasPPDMLoader Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TexasPPDMLoader
          path: D:\a\TexasPPDMLoader\TexasPPDMLoader\TexasPPDMLoader\bin\Release\net7.0\win-x64\publish\TexasPPDMLoader.exe

      - name: Create release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.versionNumber }}
          release_name: Release V${{ github.event.inputs.versionNumber }}
          
      - name: Download site content TexasPPDMLoader
        uses: actions/download-artifact@v2
        with:
          name: TexasPPDMLoader
          
      - name: Upload TexasPPDMLoader release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./TexasPPDMLoader.exe
          asset_name: TexasPPDMLoader.exe
          asset_content_type: application/octet-stream
